name: test
description: test
author: keyhan

on:
  push:
    jobs:  
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build <my project>
      



  
